name:         qedb
version:      0.0.0
author:       Herman Bergwerf <hermanbergwerf@gmail.com>
description:  Database of mathematical proofs using PostgreSQL
homepage:     https://github.com/qedb/qedb
environment:
  sdk:        '>=1.8.0 <2.0.0'
dependencies:
  rpc:          ^0.5.7
  yaml:         ^2.1.12
  eqlib:        ^0.15.0
  postgresql:   ^0.3.4+1
  shelf:        ^0.6.7+2
  shelf_rpc:    ^0.0.3+2
  shelf_route:  ^0.14.3
  logging:      ^0.11.3+1
  logging_handlers: ^0.8.0
dev_dependencies:
  # Testing
  json_object:  ^1.0.19+1
  crypto:       ^2.0.1
  http:         ^0.11.3+9
  csv:          ^3.1.1
  # UI
  htgen:        ^0.0.1
  sass:         ^1.0.0-alpha
  browser:      ^0.10.0+2
  editex:       ^0.2.2+3
  qedb_client:  ^0.1.2
  shelf_static: ^0.2.4
  transform_sass: ^0.1.0

transformers:
- $dart2js:
    commandLineOptions: [--enable-experimental-mirrors]
- transform_sass:
    $include: web/snippets/*.scss
