name:         eqdb
version:      0.0.0
author:       Herman Bergwerf <hermanbergwerf@gmail.com>
description:  PostgreSQL backend for EqDB
homepage:     https://github.com/eqdb/eqdb
environment:
  sdk:        '>=1.8.0 <2.0.0'
dependencies:
  rpc:          ^0.5.7
  yaml:         ^2.1.12
  eqlib:        ^0.5.0
  postgresql:   ^0.3.4+1
  shelf:        ^0.6.7+2
  shelf_rpc:    ^0.0.3+2
  shelf_route:  ^0.14.3
  logging:      ^0.11.3+1
  logging_handlers: ^0.8.0
dev_dependencies:
  json_object:  ^1.0.19+1
  crypto:       ^2.0.1
  http:         ^0.11.3+9
  csv:          ^3.1.1

  browser:      ^0.10.0+2
  katex_js:     ^0.1.0+1
  editex:       ^0.0.5
  eqdb_client:  ^0.0.3
