name:         eqpg
version:      0.0.0
author:       Herman Bergwerf <hermanbergwerf@gmail.com>
description:  PostgreSQL backend for EqDB
homepage:     https://github.com/eqdb/eqpg
environment:
  sdk:        '>=1.8.0 <2.0.0'
dependencies:
  rpc:        ^0.5.7
  postgresql: ^0.3.4+1
