bootstrap.href:
  https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css
bootstrap.integrity:
  sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ
katex.js.src:
  https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.js
katex.css.href:
  https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.css
editex.css.href:
  http://0.0.0.0:8083/packages/editex/editex.css
editex_form.dart.js.src:
  http://0.0.0.0:8083/notebook/src/editex_form.dart.js
